### ========= PRODUCT API ============

GET http://127.0.0.1:8000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MjMxMjE1LCJpYXQiOjE3MzgyMjk0MTUsImp0aSI6IjRhMmE4OGNkOWZmNTQ2NzRiZjYzZjIwN2RlOTM3YjJkIiwidXNlcl9pZCI6OH0.1YmMnQrVuJdbcE_Y7I6yXVfTQ0dH82g-5rlC3OVT7aQ

### =========== CUSTOMER LOGIN API =============

POST http://127.0.0.1:8000/log/login/
Content-Type: application/json

{"phone":"2222222222","password":"123"}



### =========== SIGNUP API =============

POST http://127.0.0.1:8000/log/signup/
Content-Type: application/json

{"name":"Sundar","phone":"2222222222","password":"123","region":"rajapalayam","role":"head"}

### ========== CARD DETAILS API ==========

GET http://127.0.0.1:8000/api/cards-details/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MzY4MDMxLCJpYXQiOjE3MzkzNjYyMzEsImp0aSI6IjMwMTc1YzIwMjI4ZjQ1N2U4YjdjYTQ4NzEyZjdmOWYzIiwidXNlcl9pZCI6MTZ9.ZKugN8QyAFXtaP3CchA895WD6g9UVphB6Idx_YIkhDY

### ========== CARD POST API ==========

POST http://127.0.0.1:8000/api/cards/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MzY3MDg5LCJpYXQiOjE3MzkzNjUyODksImp0aSI6ImYzZjZkMmI1MWQ0MDRiNmViMDRmYzZmMTJmMDUzZjU1IiwidXNlcl9pZCI6MTZ9.Gs1jv8_pCv0yX1untblT84nL88njLdrvjozVZMfOuzA

{"model":"Purifier IO", "customer_code":16, "customer_name":"oo", "region":"oo", "date_of_installation":"2025-02-12", "address":"oo", "warranty_start_date":"2025-02-16", "warranty_end_date":"2025-05-16"}

### ======== GET CARD =========

GET http://127.0.0.1:8000/api/cards/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MzY3MDg5LCJpYXQiOjE3MzkzNjUyODksImp0aSI6ImYzZjZkMmI1MWQ0MDRiNmViMDRmYzZmMTJmMDUzZjU1IiwidXNlcl9pZCI6MTZ9.Gs1jv8_pCv0yX1untblT84nL88njLdrvjozVZMfOuzA


### =========== NEXT SERVICE ============

GET http://127.0.0.1:8000/utils/next-service/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NDU0MTMwLCJpYXQiOjE3Mzk0NTIzMzAsImp0aSI6IjdkYWZhNzNlYzRhYzQ5MmE5MzVlZTE1NzlhMzgwNDE4IiwidXNlcl9pZCI6MTV9.fiCconew8eEwtiIUj3txqXHRgCVhpVc4zFg23yEpBxM


### ======== GET USER BY ID ==========

GET http://127.0.0.1:8000/utils/getuserbyid/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NDU2MjYzLCJpYXQiOjE3Mzk0NTQ0NjMsImp0aSI6ImVkNzQzMmU0YmVmODRhOTY4Y2Q4ZTkyNTU3NDI2YzA0IiwidXNlcl9pZCI6MTV9.UmsK75M5yKjcLosBrowahXYV0NnBtkwc9IdxwXhsB9U

### ======== HEAD ACCEPT REQUESTED EDIT ==========

GET http://127.0.0.1:8000/utils/headeditreq/7
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NDU3NTc0LCJpYXQiOjE3Mzk0NTU3NzQsImp0aSI6IjZkMmU1ZmM1ZWNkMjQwNjM5NzVlNTU4OWNhNDNiNDdjIiwidXNlcl9pZCI6MTh9.cc7e5IW-XF8mM9kSJ0bqt027lsF6TkhD7QPsCJsFzhs
