### ========= PRODUCT API ============

GET http://127.0.0.1:8000/products/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM4MjMxMjE1LCJpYXQiOjE3MzgyMjk0MTUsImp0aSI6IjRhMmE4OGNkOWZmNTQ2NzRiZjYzZjIwN2RlOTM3YjJkIiwidXNlcl9pZCI6OH0.1YmMnQrVuJdbcE_Y7I6yXVfTQ0dH82g-5rlC3OVT7aQ

### =========== CUSTOMER LOGIN API =============

POST http://127.0.0.1:8000/log/login/
Content-Type: application/json

{"phone":"9078563411","password":"123"}

# ====== DEMO 1 ========

# ----- HEAD : 9876543120 ---------
# ----- STAFF : 9123456780 --------
# ----- CUSTOMER/USER : 9182736450 ------

# ======= DEMO 2 ==========

# ------ HEAD : 7856341290 --------
# ------ STAFF : 8796054321 -------
# ------ CUSTOMER : 9078563412 ----

# ======= DEMO 3 ==========

# ------ HEAD : 7856341299 --------
# ------ STAFF : 8796054322 -------
# ------ CUSTOMER : 9078563411 ----

# ======= DEMO 4 ===========

# ------ HEAD : 7856341999 --------
# ------ STAFF : 8796054202 -------
# ------ CUSTOMER : 9078563101 ----

# ======= DEMO 5 ===========

# ------ HEAD : 9876543210 --------
# ------ STAFF : 8765432109 -------
# ------ CUSTOMER : 7654321098 ----

# ======= DEMO 6 ===========

# ------ HEAD : 9876543210 --------
# ------ STAFF : 8765432109 -------
# ------ CUSTOMER : 4321098765 ----


### =========== SIGNUP API =============

POST http://127.0.0.1:8000/log/signup/
Content-Type: application/json

{"name":"Vijay","phone":"7856341999","password":"123","region":"chennai","role":"head"}

### ========== CARD DETAILS API ==========

GET http://127.0.0.1:8000/api/cards-details/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5ODY4MTg4LCJpYXQiOjE3Mzk4NjYzODgsImp0aSI6ImM3YzViMDU2ZGZjZjQzN2NhMGVlZWI0Zjc0N2ZmNzQ5IiwidXNlcl9pZCI6MjV9.j67W4vCRTjO4igX_jK-4u0389iuCe45MAfpiFubLP5M

### ========== CARD POST API ==========

POST http://127.0.0.1:8000/api/cards/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MzY3MDg5LCJpYXQiOjE3MzkzNjUyODksImp0aSI6ImYzZjZkMmI1MWQ0MDRiNmViMDRmYzZmMTJmMDUzZjU1IiwidXNlcl9pZCI6MTZ9.Gs1jv8_pCv0yX1untblT84nL88njLdrvjozVZMfOuzA

{"model":"Purifier IO", "customer_code":16, "customer_name":"oo", "region":"oo", "date_of_installation":"2025-02-12", "address":"oo", "warranty_start_date":"2025-02-16", "warranty_end_date":"2025-05-16"}

### ======== GET CARD =========

GET http://127.0.0.1:8000/api/cards/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5MzY3MDg5LCJpYXQiOjE3MzkzNjUyODksImp0aSI6ImYzZjZkMmI1MWQ0MDRiNmViMDRmYzZmMTJmMDUzZjU1IiwidXNlcl9pZCI6MTZ9.Gs1jv8_pCv0yX1untblT84nL88njLdrvjozVZMfOuzA


### =========== NEXT SERVICE ============

GET http://127.0.0.1:8000/utils/next-service/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NDU0MTMwLCJpYXQiOjE3Mzk0NTIzMzAsImp0aSI6IjdkYWZhNzNlYzRhYzQ5MmE5MzVlZTE1NzlhMzgwNDE4IiwidXNlcl9pZCI6MTV9.fiCconew8eEwtiIUj3txqXHRgCVhpVc4zFg23yEpBxM


### ======== GET USER BY ID ==========

GET http://127.0.0.1:8000/utils/getuserbyid/16
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NDU2MjYzLCJpYXQiOjE3Mzk0NTQ0NjMsImp0aSI6ImVkNzQzMmU0YmVmODRhOTY4Y2Q4ZTkyNTU3NDI2YzA0IiwidXNlcl9pZCI6MTV9.UmsK75M5yKjcLosBrowahXYV0NnBtkwc9IdxwXhsB9U

### ======== HEAD ACCEPT REQUESTED EDIT ==========

GET http://127.0.0.1:8000/utils/headeditreq/2
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjg1ODU3LCJpYXQiOjE3NDAyODQwNTcsImp0aSI6ImJjMGQ4MWFiMzFlZDRmMzRhZTcxNjVkODRiN2JjZmNmIiwidXNlcl9pZCI6MjR9.lynpxwa9tVbFi_ki9axQKy-BmYUJaeby8Uh9CuGJWrI

### ======== CREATE CARD BY HEAD ==========

POST http://127.0.0.1:8000/api/headcreatecard/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzU3Mzg4LCJpYXQiOjE3NDAzNTU1ODgsImp0aSI6IjljMjRhZWQ5NTA1MDQxNTA4M2NkMDZhMWI5NmMwNGMzIiwidXNlcl9pZCI6MjR9.pEBO4O1rEaOnLVIjTQK0G1hPu_pq-hBZKnw7w6f_wJU

{"model": "Test Card", "customer_code": 25, "customer_name": "Placeholder", "region": "rajapalayam", "address": "Placeholder", "date_of_installation": "2025-02-25", "warranty_start_date": "2025-02-25", "warranty_end_date": "2025-02-27", "acm_start_date": "", "acm_end_date": "", "contract_start_date": "", "contract_end_date": ""}

### ======== GET CARD BY HEAD ==========

GET http://127.0.0.1:8000/api/headcardlist/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NjAzOTg3LCJpYXQiOjE3Mzk2MDIxODcsImp0aSI6ImFhZGEzOGRmNDlkMzRhYzI4MGZkZDViNmQ4YjI4Y2E3IiwidXNlcl9pZCI6MTl9.uu0L-UxDjg6zYCmgvtQVtYULHgENYCw0T-lQRcZxCVM

###========== EDIT CARD BY HEAD USING ID ========

PATCH http://127.0.0.1:8000/api/headeditcard/5/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NjAyMjY2LCJpYXQiOjE3Mzk2MDA0NjYsImp0aSI6IjA3NDhlMzdkMDAxZjQ3ZjE4ODhiNGY3ZjJiZTQ2ZGQyIiwidXNlcl9pZCI6MTl9.Ntm5WtjS2nTW_61RDwYxeW3Rx79bfkZ8_fQ8wjNltes

{
    "model":"Purifier Mark II", 
    "customer_code":16, 
    "customer_name":"oo", 
    "region":"oo", 
    "date_of_installation":"2025-02-12", 
    "address":"oo", 
    "warranty_start_date":"2025-02-16", 
    "warranty_end_date":"2025-05-16"
}

### ========= CREATE SERVICE ENTRIES =========

POST http://127.0.0.1:8000/api/createserviceentry/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NzE1MDkxLCJpYXQiOjE3Mzk3MTMyOTEsImp0aSI6ImNlOGJkZDYxNTUxMzQwMGU4NjY2ODhmZDI3MGMyNmNhIiwidXNlcl9pZCI6MTl9.4XcqzPhxVmM1F-jV2xIkSMkLfH-QBRtyl-O7tQ0BGTQ

{
    "card":3, 
    "date":"2025-02-15", 
    "next_service":"2025-05-12", 
    "visit_type":"C", 
    "nature_of_complaint":"None", 
    "work_details":"Check the working of purifier", 
    "parts_replaced":"No", 
    "icr_number":"5354",
    "amount_charged":"5000",
    "customer_signature":{"sign":0},
    "cse_signature":{"sign":0}
}

### ========= SIGN SERVICE ENTRIES =========

PATCH http://127.0.0.1:8000/api/signbycustomer/9/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5ODY4NjI5LCJpYXQiOjE3Mzk4NjY4MjksImp0aSI6IjZjNjExMjdiYTljMDRjMTY5MWVjZGNiZjhhNTkxODVmIiwidXNlcl9pZCI6MjV9.8JRdeLWx3P8_FZ6cEPzHcmd1Ft5wRfJx1KLfiFmY658

{
    "customer_signature":{"sign":0},
    "feedback":"Good",
    "rating":1
}

### ======== UNAVAILABLE REQ ============

POST http://127.0.0.1:8000/unavailablereq/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMzc1NDg1LCJpYXQiOjE3NDAzNzM2ODUsImp0aSI6ImYxMGI0NmJjMDViZjQ3OGY5M2RlNzIzZGM2NGFmZDJjIiwidXNlcl9pZCI6MjZ9.xKqb8MAPUmi5YNW5zvjYtOeJNyRjtAppcf9rK8Ka9jQ

{
    "service":21,
    "staff":21
}

### ========= REASSIGN REQ ============

POST http://127.0.0.1:8000/utils/reassingstaff/3
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMjkwNDIwLCJpYXQiOjE3NDAyODg2MjAsImp0aSI6IjhlYTg2ODJhMzZhYTRkZGY4NjIwNmEyODJhYjkwODY3IiwidXNlcl9pZCI6MjR9.p4gYFCudg0z5BXJKpQywlKailb67W2Bz4yY6K4Jpb4Q

{}

### ======== CANCEL SERVICE BY CUSTOMER =======

PATCH http://127.0.0.1:8000/services/cancleservicebycustomer/22
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5NjMxMDk0LCJpYXQiOjE3Mzk2MjkyOTQsImp0aSI6IjA5ZWUzYjYzZWI5YTRhNGY5OGVmOTM0NmZiZWNlOTYwIiwidXNlcl9pZCI6MjJ9.q-OeWLVtc8C5ZTEHhTKddLEAUzgu5t3SR_Y5gdIXzfY

{}  

### ======== CHECK AVAILABILTY =========

POST http://127.0.0.1:8000/utils/checkstaffavailability/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzM5ODAyNjcyLCJpYXQiOjE3Mzk4MDA4NzIsImp0aSI6ImViMGFjNGZiNWQ2ZTQ2NDRiYmVhMGM1YjM5ZmRmOWQ3IiwidXNlcl9pZCI6MjV9.WZGEzqpSkDEXBwuqOYDXIlQAGHEpfiG81Y8LBFhLBKA

{
    "from_date":"2025-02-15",
    "to_date":"2025-02-17"
}

### ======== EDIT USER ============

POST http://127.0.0.1:8000/utils/edituserxxx/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMDM2MTgyLCJpYXQiOjE3NDAwMzQzODIsImp0aSI6ImMxMWRkNWY4MDY1NjQ0NTdhMjM2ODdkNjdjNDQ5MTRhIiwidXNlcl9pZCI6MjR9.8bUuLInHGPNZqDf7hzY06wcq5rX8ScN76gWNYYRk4xs

{
    "id": 25,
    "name": "Kishor",
    "phone": "9078563412",
    "email": "kishor3780@gmail.com",
    "address": "58, Fisherman Street,",
    "city": "Chandrapady,",
    "district": "Maiyladuthurai",
    "postal_code": "609 307",
    "region": "rajapalayam"
}

### ======== GET ALL EDIT REQ =========

GET http://127.0.0.1:8000/utils/headvieweditreq/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQwMTk0MzQ3LCJpYXQiOjE3NDAxOTI1NDcsImp0aSI6ImM1MjA1ODAxNmQyNjRkYTdiM2M2OTY3NzM2Nzg0ZGNjIiwidXNlcl9pZCI6MjR9.K7pYdaSjvIYv_PoXJ5t_7-6M22uFgmBRH9-nJWZukTI

