# Generated by Django 5.1.4 on 2025-02-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_state_user_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='availability',
            field=models.JSONField(default={'unavailable': []}),
        ),
        migrations.AddField(
            model_name='user',
            name='last_service',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
