# Generated by Django 5.1.4 on 2025-02-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_availability_user_last_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability',
            field=models.JSONField(default=dict),
        ),
    ]
