# Generated by Django 5.1.4 on 2025-02-04 09:17

import user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='availability',
            field=models.JSONField(default=user.models.User.default_availability),
        ),
    ]
