# Generated by Django 5.1.4 on 2025-02-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('customer', 'Customer'), ('worker', 'Worker'), ('admin', 'Admin'), ('head', 'Head')], default='user', max_length=10),
        ),
    ]
