# Generated by Django 5.1.4 on 2025-02-12 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('rajapalayam', 'Rajapalayam'), ('ambasamuthiram', 'Ambasamuthiram'), ('sankarankovil', 'Sankarankovil'), ('tenkasi', 'Tenkasi'), ('tirunelveli', 'Tirunelveli'), ('chennai', 'Chennai')], max_length=255),
        ),
    ]
