# Generated by Django 5.1.4 on 2025-03-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='FCM_Token',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
