# Generated by Django 5.1.4 on 2025-02-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editReq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='editreq',
            name='customer',
            field=models.CharField(default=9, max_length=255),
            preserve_default=False,
        ),
    ]
