# Generated by Django 5.1.4 on 2025-02-22 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editReq', '0002_editreq_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='editreq',
            name='staff_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
