# Generated by Django 5.1.4 on 2025-01-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(default={'password': '123'}, max_length=100),
            preserve_default=False,
        ),
    ]
