# Generated by Django 5.1.4 on 2025-01-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=255)),
                ('worker_id', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('IND', 'India'), ('USA', 'United States'), ('AUS', 'Australia')], max_length=10)),
                ('status', models.CharField(choices=[('BD', 'Booked'), ('SD', 'Service Duration'), ('SD', 'Serviced'), ('NS', 'Not Serviced'), ('CC', 'Service Cancelled By Customer'), ('CW', 'Service Cancelled By Worker')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
