# Generated by Django 5.1.4 on 2025-01-25 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('BD', 'Booked'), ('SP', 'Service Period'), ('SD', 'Serviced'), ('NS', 'Not Serviced'), ('CC', 'Service Cancelled By Customer'), ('CW', 'Service Cancelled By Worker')], max_length=10),
        ),
    ]
