# Generated by Django 5.1.4 on 2025-01-26 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_service_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='compliant',
            field=models.CharField(choices=[('IND', 'India'), ('USA', 'United States'), ('AUS', 'Australia')], default='Yearly Maintance', max_length=255),
            preserve_default=False,
        ),
    ]
