# Generated by Django 5.1.4 on 2025-01-26 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_service_compliant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='compliant',
            new_name='complaint',
        ),
    ]
