# Generated by Django 5.1.4 on 2025-02-03 09:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_service_available_alter_service_complaint'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='customer_id',
        ),
        migrations.AddField(
            model_name='service',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='customer_data',
            field=models.JSONField(default={'data': 'none'}),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='complaint',
            field=models.CharField(choices=[('GS', 'General Service'), ('WL', 'Water Leakage'), ('WTB', 'Water Taste Bad')], default='GS', max_length=255),
        ),
        migrations.AlterField(
            model_name='service',
            name='region',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='service',
            name='worker_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
