# Generated by Django 5.1.4 on 2025-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_service_worker_id_service_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='complaint',
            field=models.CharField(max_length=255),
        ),
    ]
