# Generated by Django 5.1.4 on 2025-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_alter_service_complaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.JSONField(default='jj'),
            preserve_default=False,
        ),
    ]
