# Generated by Django 5.1.4 on 2025-02-03 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
