# Generated by Django 5.1.4 on 2025-02-04 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='date_of_service',
            field=models.CharField(default='Service Not Done Yet', max_length=255),
        ),
        migrations.AddField(
            model_name='service',
            name='staff_name',
            field=models.CharField(default='Manikam', max_length=255),
            preserve_default=False,
        ),
    ]
