# Generated by Django 5.1.4 on 2025-02-09 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0011_service_date_of_service_service_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='available_date',
            field=models.CharField(default='2025-09-12', max_length=255),
            preserve_default=False,
        ),
    ]
