# Generated by Django 5.1.4 on 2025-02-11 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_customer_code'),
        ('service', '0012_service_available_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='card',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='card', to='card.card'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='service',
            name='feedback',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='rating',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(choices=[('BD', 'Booked'), ('SD', 'Serviced'), ('NS', 'Not Serviced'), ('CC', 'Service Cancelled By Customer'), ('CW', 'Service Cancelled By Worker')], max_length=10),
        ),
    ]
