# Generated by Django 5.1.4 on 2025-02-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_service_card_service_feedback_service_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='rating',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
