# Generated by Django 5.1.4 on 2025-03-26 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='on_warrenty',
            field=models.BooleanField(default=False),
        ),
    ]
