# Generated by Django 5.1.4 on 2025-05-04 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0017_alter_service_staff_alter_service_staff_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='on_ACM',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='service',
            name='on_contract',
            field=models.BooleanField(default=False),
        ),
    ]
