# Generated by Django 5.1.4 on 2025-02-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unavailableReq', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unavailablereq',
            name='staff_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
