# Generated by Django 5.1.4 on 2025-01-03 04:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('customer_code', models.CharField(max_length=100, unique=True)),
                ('date_of_installation', models.DateField()),
                ('address', models.TextField()),
                ('warranty_start_date', models.DateField()),
                ('warranty_end_date', models.DateField()),
                ('acm_start_date', models.DateField(blank=True, null=True)),
                ('acm_end_date', models.DateField(blank=True, null=True)),
                ('contract_start_date', models.DateField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('visit_type', models.CharField(choices=[('I', 'Installation'), ('C', 'Complaint'), ('MS', 'Mandatory Service'), ('CS', 'Contract Service'), ('CC', 'Courtesy Call')], max_length=10)),
                ('nature_of_complaint', models.TextField(blank=True, null=True)),
                ('work_details', models.TextField()),
                ('parts_replaced', models.TextField(blank=True, null=True)),
                ('icr_number', models.CharField(blank=True, max_length=50, null=True)),
                ('amount_charged', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer_signature', models.JSONField(blank=True, null=True)),
                ('cse_signature', models.JSONField(blank=True, null=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_entries', to='card.card')),
            ],
        ),
    ]
