# Generated by Django 5.1.4 on 2025-01-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='customer_name',
            field=models.CharField(default='None', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='card',
            name='region',
            field=models.CharField(choices=[('IND', 'India'), ('USA', 'United States'), ('AUS', 'Australia')], default='IND', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='customer_code',
            field=models.CharField(max_length=100),
        ),
    ]
