# Generated by Django 5.1.4 on 2025-02-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0002_card_customer_name_card_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='next_service',
            field=models.DateField(default='2025-06-08'),
            preserve_default=False,
        ),
    ]
