# Generated by Django 5.1.4 on 2025-02-12 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0004_alter_card_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='region',
            field=models.CharField(choices=[('rajapalayam', 'Rajapalayam'), ('ambasamuthiram', 'Ambasamuthiram'), ('sankarankovil', 'Sankarankovil'), ('tenkasi', 'Tenkasi'), ('tirunelveli', 'Tirunelveli'), ('chennai', 'Chennai')], max_length=255),
        ),
    ]
