# Generated by Django 5.1.4 on 2025-02-13 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0005_alter_card_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='region',
            field=models.CharField(max_length=255),
        ),
    ]
