# Generated by Django 5.1.4 on 2025-02-16 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0006_alter_card_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceentry',
            name='service',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
