# Generated by Django 5.1.4 on 2025-01-25 15:41

import products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('features', models.JSONField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=products.models.product_image_upload_to)),
            ],
        ),
    ]
